-- INCLUINDO VÁRIOS REGISTROS AO MESMO TEMPO

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA, [NOME], [PERCENTUAL COMISSAO]])
VALUES 
('00235', 'Marcio Almeida Silva', 0.08),
('00236', 'Claudia Morais', 0.08);