INSERT INTO [TABELA DE PRODUTOS]   -- INSIRA NA
([CODIGO DO PRODUTO],              -- INSERE NO NOMES DOS CAMPOS
[NOME DO PRODUTO],
[[EMBALAGEM],
[[TAMANHO],
[SABOR],
[PRECO LISTA])
VALUES								-- OS VALORES DOS CAMPOS
('1040107', 
'Light - 350 ml - Melância',
'Lata',
'350 ml',
'Melância',
4.56);

-- INCLUINDO OS REGISTROS AO MESMO TEMPO

INSERT INTO [TABELA DE PRODUTOS]   -- INSIRA NA
([CODIGO DO PRODUTO],              -- INSERE NO NOMES DOS CAMPOS
[NOME DO PRODUTO],
[[EMBALAGEM],
[[TAMANHO],
[SABOR],
[PRECO LISTA])
VALUES								-- OS VALORES DOS CAMPOS
('1037797', 
'Clean - 2 litros - Laranja',
'PET',
'2 Litros',
'Laranja',
16.01);

INSERT INTO [TABELA DE PRODUTOS]   -- INSIRA NA
([CODIGO DO PRODUTO],              -- INSERE NO NOMES DOS CAMPOS
[NOME DO PRODUTO],
[[EMBALAGEM],
[[TAMANHO],
[SABOR],
[PRECO LISTA])
VALUES								-- OS VALORES DOS CAMPOS
('1000889', 
'Sabor da Montanha - 700 ml - Uva',
'Garrafa',
'700 ml',
'Uva',
6.31);