-- INCLUINDO DADOS NA TABELA

INSERT INTO [TABELA DE PRODUTOS]   -- INSIRA NA
([CODIGO DO PRODUTO],              -- INSERE NO NOMES DOS CAMPOS
[NOME DO PRODUTO],
[[EMBALAGEM],
[[TAMANHO],
[SABOR],
[PRECO LISTA])
VALUES								-- OS VALORES DOS CAMPOS
('1040107', 
'Light - 350 ml - Melância',
'Lata',
'350 ml',
'Melância',
4.56);